### ISSUE TITLE
Implement unit tests

### ISSUE THREAD

**Issue by chrisallenlane** [cheat/cheat#17]
Will have to research how this is best handled in Python.

**Comment by chhsiao90** [comment]
It seems some new feature need wait for unit test implemented, so that cheat could keep stable and reliable.
I would like to help on this if you hadn't start on this!
Actually, I had a WIP branch that implement unit test for cheats.py at 636e9f5f39b6699a597731833c5a2a49b25bec72.

That my idea is cheat will use lot of user environment, like path or variables, that would different between server and server.
So we need to do is mock them.

If there is no big problem, I will try finish them soon!

**Comment by chrisallenlane** [comment]
Closing as resolved - nearly 7 years later - with the release of `cheat` v3.
