### ISSUE TITLE
Proposal: re-implement cheat in Golang

### ISSUE THREAD

**Issue by chrisallenlane** [cheat/cheat#470]
Hi, all

I am soliciting opinions on the following proposal:

**I propose that we re-implement `cheat` (from scratch) in [Go][].**

### Problems ###
In my opinion, Python is harming the project, primarily for two reasons:

#### I am not a Python developer ####
`cheat` initially began as a small personal project to help me learn Python. I wrote it over the course of a weekend, after which time I lost interest in Python entirely. (It's a fine language, but not for me.)

This has become a major problem, in that my inexperience with Python has massively hamstrung my ability to lead this project. (This is, of course, _my_ problem rather than Python's problem, but it's a problem nonetheless.)

#### Cross-platform compatibility in Python is proving difficult ####
The Python ecosystem itself is also causing us some major headaches here, in that [many of the open tickets are either directly or indirectly related to issues pertaining to the installer][issues]. The project is currently plagued with cross-platform compatibility issues, driven primarily by differences among Linux/OSX/Windows environments, and also by differences between Python 2 and Python 3.

A noble effort was made to mitigate these issues by packaging `cheat` in Docker and a `snap` container. These efforts, however, have introduced their own issues, due to nuances regarding the sandboxing of containerized applications.

We have collectively spent an unjustifiable amount of time in attempting to resolve these cross-platform compatibility issues. `cheat` is an incredibly simple application (it can and has been competently re-implemented as simple bash scripts), and it's absurd that such a lightweight application should be encumbered by this complexity.

### The case for Go ###
I believe that re-implementing `cheat` in Go will solve these problems, in that:

1. I am personally a competent Go developer
2. Go (should) give us reliable cross-platform compatibility "for free"
3. The Go "installer" need only be "download the binary to somewhere and run it". It should be easy to package a Go application for any platform.

Typically, I am wary of the "burn it down and start over" approach - especially for relatively mature software. (I believe `cheat` is now 6 or 7 years old.) With that said, `cheat` is a simple application, and I don't think a re-write would be a huge undertaking.

### Proposal ###
So, I propose the following:

1. We (I) re-write `cheat`, from scratch, in Go.
2. We shed some legacy baggage in doing so, especially regarding envvars and configuration. _Backwards compatibility will not be a priority when re-implementing cheat!_ Instead, the goal will be to refactor and simplify the application, given the lessons we've learned so far.
3. We take this opportunity to implement some frequently-requested features, including:
  a. Support for nested cheatsheet subdirectories
  b. Better handling of local/global cheatsheets
  c. Better interoperability with similar projects. (We've been talking for _years_ now about externalizing cheatsheets to a standalone repository.)
4. Make a decision regarding this repository: we can either archive it, rename it, fork the exiting codebase onto a `python` branch (and dedicate `master` to the Go refactoring), or perhaps create a new repository, like `cheat/cheat-go`. (I'm particularly interested in feedback on this point. Please share your thoughts.)

### Feedback ###
Please share your thoughts regarding refactoring into Go, and/or share some features that you'd like to see in a hypothetical new version of `cheat`. I'm interested in feedback both from contributors and users.

@TomasKorbar, @bernermic - I'm particularly interested in your input as well, given your experience maintaining some of `cheat`'s "downstream" packages.

Thanks, everyone :slightly_smiling_face: 

[Go]: https://golang.org/
[issues]: https://github.com/cheat/cheat/issues?q=is%3Aissue+is%3Aopen+label%3Ainstaller

**Comment by bernermic** [comment]
Hey,

for the snap packaging this is not an issue, as there is go support given 😀

I have no experience yet in go but this should not be an issue.
I‘m looking forward to have a look into this.

Greetings 
Michael

**Comment by DerMolly** [comment]
I would suggest to develop this new cheat in a separate repository. This way unitl it's finished everyone can use the this repo. And afterwards one can change the README to point to the new repo, so every link to cheat's repo stays the same and everyone from google or such get's to know about the new repo.

**Comment by m3nu** [comment]
Glad to see this. I already implemented `cheat` in Go as personal exercise. Feel free to reuse any part.

https://github.com/m3nu/go-cheat

**Comment by pirat89** [comment]
For me it's sad a little as Python is installed on bigger amount of machines than golang by default and cheat was fine in that case even on older machines easily - ok, depends on installation method :) ... But I think that it could be good step for another version of cheat If you feel better with Golang than Python. In such case, please release new version of cheat with bump of the major version - 3.x.x - once it is prepared.

**Comment by DerMolly** [comment]
the golang cheat would most likely have a binary release, so you would not need to have golang installed. Installing it should be as easy as installing any other software on your computer

**Comment by TomasKorbar** [comment]
Hi guys,
My experience with Cheat as a maintainer is good but that can be caused by my presence at one of the major refactors where i tried to make cheat as much linux/fedora friendly as i could. I see that over the time after refactor, unexpected issues were popping up mainly with cross-platform compatibility. So i want to ask you both @m3nu @chrisallenlane. Are you sure that re-implementation in golang will provide compatibility across our all 3 major platforms (linux, windows, mac)?

3.a + 3.b Great ideas.
3.c Best idea of all. This will help me with maintaining, because cheat package will not be forced to install cheat sheets.
4. in my opinion master should be dedicated to the most recent development, so go implementation should go there and python should be moved into its own branch. I thought about moving it to its own repository but that would result in division of community and i do not think that would be good for cheat. And at last as pirat89 said please bump major release version to 3.

The biggest upside of this i see in your knowledge of golang. If you are as you say a competent go developer then developing cheat will be much easier (and fun:)) for you in golang than in python.

There is one last thing that i want to ask you to be careful about. Choice of dependencies. Please use common go packages because if they will not be present in Fedora then i will have to package (and maintain) them. I'm not saying i will not do it but just a tip how to make my life a little bit easier:)
I took a look at the m3nus implementation and i can already see that "github.com/gobuffalo/packr/v2" is not in Fedora.
Unfortunately i am not experienced in go, so some of my questions or opinions will be maybe wrong. Please correct me at those if necessary.

**Comment by m3nu** [comment]
With Go one would usually cross-compile a binary for all platforms and then package that. So it's neither necessary to have Go installed locally or to have dependencies in a distro.

Since many distros aim for reproducible builds, this should be taken into account as well. But I don't think this will be an [issue](https://blog.filippo.io/reproducing-go-binaries-byte-by-byte/).

I also started to implement some basic deb/rpm packaging using [NFPM](https://github.com/goreleaser/nfpm). For reproducible builds, we could use a Docker file to build and package for different distros.

**Comment by TomasKorbar** [comment]
In Fedora all packaged software must be rebuild-ed before release. No prebuilt binaries are allowed.
Unfortunately NFPM will not help me. All packages must have their own spec file with information about them, dependencies, process of build etc (that is ok, it is quite easy to write). That file is parsed by rpm-build and then rpm packages are created with binaries and all files of software which can be then distributed to users.

**Comment by m3nu** [comment]
Thought so. But a Docker image for building it would be OK? It doesn't really matter, which tool is building the package. I'm sure rpm-build works too.

**Comment by TomasKorbar** [comment]
> Thought so. But a Docker image for building it would be OK?
Actually i may have an idea here. Recently new tool and github application was released. Its name is packit (on marketplace Packit-as-a-service)and its goal is to make upstream and downstream more close. If you and Chriss would agree then we could try to configure it here. That way there could be only one specfile and you could see if changes done in project does not break Fedoras package.
> It doesn't really matter, which tool is building the package. I'm sure rpm-build works too.
Actually only tool which builds official packages for Fedora is rpmbuild because all official releases are built in https://koji.fedoraproject.org/koji/ according to specfile. But in upstream you are right. Chriss can use whatever he sees fit to build cheat's upstream rpm package if he wants to provide one.

**Comment by chrisallenlane** [comment]
Hi, guys

I apologize for my tardiness here. I've begun a new job recently, which is always hectic.

I appreciate the wonderful feedback here. I have some news to share as well:

I've actually done a _significant_ amount of work on the "version 3" cheat, implemented in Golang. In fact, I'm giving a talk about it on Friday, which gives me a **strong** impetus to finish it this week! (It is already very, very close.)

It is a massively superior piece of software. In addition to relieving the pain we've encountered with regards to packaging, cheat 3:

- allows for nested cheatsheets, to an arbitrary depth! (This has been a highly requested feature for years
- provides syntax highlighting for multiple languages. The languages may be specified at-will via optional support for "front-matter" within the cheatsheets
- provides optional "tagging" of cheatsheets for filtering, likewise via front-matter
- externalizes the cheatsheets from the executable entirely. Later this will, I will create a `cheat/cheatsheets` repository, which has likewise often been discussed and requested over the years
- provides for simpler configuration: all configuration is now handled by a single YAML config file
- has few dependencies
- integrates tightly (but cleanly) with `fzf` for "fuzzy" searching of cheatsheet by filepath, cheatpath, and tags (this is **incredibly** useful)
- has very extensive test coverage

As I said, I'm actually giving a talk about this later this week, so this is definitely happening. It's actually quite close to complete as-is.

@bernermic, @pirat89 - I agree with the argument regarding not wanting to create a separate repository (aside from the new cheatsheets repository, of course.)

How would you feel about me forking the current `master` to a "cheat-python" branch, before I merge the "3.0" Go code into `master`? I want to make the packaging situation as simple as possible, though there's probably going to be a little bit of pain involved here regardless.

Thanks, all. I'm very eager to release this new version shortly!

**Comment by pirat89** [comment]
@chrisallenlane +1 for cheat-python branch before merge of Go code.

**Comment by TomasKorbar** [comment]
@chrisallenlane I too agree with creation of cheat-python branch before you merge go code into master.

**Comment by chrisallenlane** [comment]
@pirat89 , @TomasKorbar - sounds good. I'm giving the v3 talk tomorrow, so I expect to create the `cheat-python` branch before publishing `v3` to `master` tonight (Oct 17).

**Comment by chrisallenlane** [comment]
@pirat89 @TomasKorbar @bernermic 

FYI, I just created the `cheat-python` branch. Feel free to re-point your packages at it, if you'd like.

I'm *mostly* going to freeze that branch now. I'll likely merge in some minor commits over the next week or two, but most of it will be pertaining to documentation or quick/easy bugfixes. That branch shall now be feature-frozen, though, and will never receive any backwards-incompatible changes.

Regarding `master`:

My talk got moved to Tuesday (Oct 22), so I'm going to take an extra day or two polish up v3 before pushing it to `master`. Once I do so, I'll update (and close) this ticket. I'll then make a pass through the open issues and pull-requests to merge/close items as appropriate.

Thanks, guys. Just shout if you have any questions or concerns.

**Comment by chrisallenlane** [comment]
Hi, all

This is now closed as _resolved_! :confetti_ball: 

Please try out `cheat` v3, and let me know if you encounter any issues. Also, be aware that the `cheat-python` branch is there if you need it.

Thanks.

**Comment by m3nu** [comment]
You probably want to run UPX on the bins before releasing them. For macOS it reduced the size by 70%. Linux and Windows look rather large too.

```
manu@nyx2: ~/Downloads $ ll cheat-darwin-amd64
-rwxr-xr-x@ 1 manu  staff   9.4M Oct 20 22:22 cheat-darwin-amd64
manu@nyx2: ~/Downloads $ upx --brute cheat-darwin-amd64
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2018
UPX 3.95        Markus Oberhumer, Laszlo Molnar & John Reiser   Aug 26th 2018

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
   9824264 ->   2977808   30.31%   macho/amd64   cheat-darwin-amd64

Packed 1 file.
manu@nyx2: ~/Downloads $ ll cheat-darwin-amd64
-rwxr-xr-x  1 manu  staff   2.8M Oct 20 22:22 cheat-darwin-amd64
```

**Comment by m3nu** [comment]
I stumbled over one thing while updating. #474. Apart from that all works as expected. Good idea with the new config and different folders. Congrats on the rewrite @chrisallenlane!

**Comment by chrisallenlane** [comment]
Thanks for the feedback and bug report, @m3nu. I appreciate it.

I hadn't heard of `upx` before. It seems very interesting, so thanks for the recommendation. I created #475 to explore it and other possibilities for reducing the size of the executables.
