### ISSUE TITLE
Choose a license (revisited)

### ISSUE THREAD

**Issue by chrisallenlane** [cheat/cheat#477]
There was [an extensive discussion regarding][discussion] `cheat`'s license some time ago. At the time, it was decided that the best option was to dual-license `cheat`, because it was questionable whether it was possible to re-license it without contributors' explicit permission.

However, the dual-license - at most - made the best of a bad situation. It was a confusing compromise.

With the v3 re-write, we have a unique opportunity here: because the code is now 100% my own, the consent of others is no longer needed to change the license. That being said, now is the time to choose the best license for the project going forward.

Please share your thoughts regarding the appropriate license below. My goals regarding the license are:

1. To remain as "libre" and "gratis" as possible
2. To make it as painless as possible for upstream stakeholders to incorporate `cheat` into their distributions

(I'll note that I'm uncertain if it's possible to change the license of the `cheatsheets` repository, because it still contains _numerous_ contributions from other authors. It may be stuck with the confusing dual-license, unfortunately.)

[discussion]: https://github.com/cheat/cheat/issues/261

**Comment by chrisallenlane** [comment]
@TomasKorbar , @pirat89, I'm curious to get your perspective here. What is Red Hat's perspective on this kind of thing?

**Comment by eMBee** [comment]
there is a difference in requirements for the license of the cheat application, and the license for the cheats themselves. for the cheats it is important that they can be used anywhere without risk, and therefore i'd recommend a BSD or MIT license for those.

for the cheat application any license would be fine, though using the same license for cheat examples and the application may be worth a consideration for simplicity's sake.

**Comment by pirat89** [comment]
We cannot tell what is RH perspective on that. We acts here just as Fedora community members. From my previous experience, data cannot be licensed and cheatsheets are from my POV just data. So I guess we should talk only about license of the cheat source code. But I am not lawyer and I can be wrong.

Anyway, for me, both licenses are ok.

**Comment by tony** [comment]
I was part of #347 

since this is a matter of snippet-like stuff:

I advise the most minimal (short, to the point), portable (forward compatible to other open source licenses as well as private software), copy-paste friendly.

As for being copy-paste friendly, MIT:
stackoverflow, in 2016, decided to make code snippets MIT license: https://meta.stackexchange.com/questions/271080/the-mit-license-clarity-on-using-code-on-stack-overflow-and-stack-exchange

> Double licensing with GPL and MIT

MIT is already forward compatible to GPL. 

"Dual licensing" just calls intent of the project into question. Are you permissively licensed or not? If someone wanted to "pick GPL", they could copy MIT code into their GPL project, or fork the whole project and make it GPL.

If you wanted to do a contract where I buy a car from you, wouldn't it be a little odd we said, 'there's two contracts, radically different terms, you can switch any time'. It'd be a little murky what we're actually doing. Do I even own the car? Did I waive my right to hold you liable if it breaks? Do you own my house if I park it in my garage? (Why should the thought come to mind?)

Hopefully that analogy makes sense. Late by me 😆

**Comment by MadeOfMagicAndWires** [comment]
Disclaimer
---

IANAL. Definitely not a copyright one.

Double licensing
------

This is moot now but as I understand it <sup>1</sup>, as far as incorporating code under a specific license, while it would still have been finicky, it suffices to keep only the derivative under the original license and specifying which files fall under that. 

This allows whatever other code you have written to stay under your chosen license, rather than having to (dual-)license the entire project.

Re-licensing
-----

> 1. To remain as "libre" and "gratis" as possible

As for the license under which to continue, the main difference between the two licenses is in how much freedom any derivative project would have. Very broadly, GPL has many protections in place to ensure any derivative code and project is distributed under open source, while MIT allows any *modified* code to be distributed as anything.

It's basically an idealogical difference between what is more libre, allowing any derivative code to be used in more ways under less restrictions or to ensure that any code will be available under the same open-source license.

There are arguments for both sides and their relevance matters on a per project basis. Personally, I like to release smaller projects under MIT while any larger project I plan to maintain, and which are more interesting for hobby developers than companies, to be licensed under GPL.

> 2. To make it as painless as possible for upstream stakeholders to incorporate `cheat` into their distributions

This is entirely possible with both licenses, as long as they provide the license in some way. And, as they (usually) don't modify the code the main differences between these two licenses does not come up. The real issue is for developers and companies who want to use or fork your code and distribute it.

Additionally, provided all code is yours and you are the copyright holder, you are allowed to change the license at any time. Any previous copies will continue to be available on the old license though (and can thus be modified and distribute under the same old license).

Cheatsheet license
-----
The re-licensing of contributed code is perhaps indeed a bit trickier and this is why a lot of projects require contributors to add a licensing notice to any new files (and in some cases even require copyright to be given over to a specific organisation).
As long as you are the only maintainer though, you are ultimately the one to merge code into the project, and there definitely is a case that any pull requests come with the implicit agreement that it is to be licensed under the same license as the rest of project. (Especially if the README says something to the effect of "all code is licensed under such and such license"). I doubt anyone will sue you over any of their contributions anyway.

As previously discussed, any code can be re-licensed under a different license as long as you own the code (which you arguably do).

Replies
----

@tony 
> MIT is already forward compatible to GPL

But not backwards, I don't know which code was initially what, but you can't re-license GPL code as MIT as it has many restrictions on use and deviation of the original code, while the MIT effectively has none.

As for shortness, GPL also has a shorter [license notice](https://www.gnu.org/licenses/gpl-howto.html) to be added code files of the project. As long as the full license is provided somewhere in the project referencing this will be enough as a file header of other files.

&nbsp;
---
1: Admittedly I have only personally done this with BSD licensed code.

**Comment by TomasKorbar** [comment]
Hi @chrisallenlane,
Unfortunately i do not have a recommendation here for you. And as @pirat89 said we are here as a members of Fedora community. I'm ok with both GPL and MIT. The choice is yours:)

**Comment by chrisallenlane** [comment]
Thanks to everyone that commented here. I read and reflected on everything that was shared.

I have decided to license `cheat` under the MIT license, which I just committed to the project. For those interested, I made that decision for the following reasons:

1. My understanding of the GPL "copyleft" license is that it intends to promote open-source software by mandating that "derivative works" of GPL-licensed software must itself be open-sourced. Given that `cheat` will likely never have derivative work, however, I don't believe that line of reasoning is applicable here. In our case, I believe we do a better job of promoting open-source by allowing others to use our open-source software, which is made easier by the MIT license.

2. While I believe that `cheat` is an enormously useful piece of software, it is in no way technologically exceptional. Should an organization desire to use `cheat` for non-free purposes, it would be a minor undertaking to re-implement it from scratch, thus bypassing our GPL-ed intentions with little effort. That being the case, the GPL does little for us.

3. Beyond the above, I have zero interest in legally enforcing a GPL license. If a licensee violated the terms of the license, I would not have the time, interest, or capital necessary to take the offender to court. 

With all of that said, I believe the MIT is the best license for `cheat` going forward.

Thanks again to everyone that shared feedback. With the license committed, I'm now closing this as resolved.
