### ISSUE TITLE
Missing dependencies in `deps.sh`

### ISSUE THREAD

**Issue by MadeOfMagicAndWires** [cheat/cheat#481]
So I've been writing an update for the PKGBUILD for this app on the AUR, and I noticed that the `deps.sh` wasn't pulling all dependencies needed for it to build successfully for me. 

The missing dependencies were these:
 `go get -u -d -v github.com/danwakefield/fnmatch`
 `go get -u -d -v gopkg.in/yaml.v2`

Now, I'm not an expert on go, and I haven't checked which parts actually need these dependencies but going by the documentation `go get` *is* supposed to pull dependencies recursively, which means that either they're missing here or a dependency package has mssing dependencies (`yaml.v1` *was* pulled by some package).

Either way I was able to fix it by adding these dependencies manually, so I think doing the same for `deps.sh` will work just fine.

**Comment by chrisallenlane** [comment]
Ah, good catch. Though I'm surprised by `danwakefield/fnmatch`. I don't recall using that, off the top of my head.

I won't bother to update `deps.sh`, because the way forward is almost certainly #480 (use Go modules). I'll prioritize getting that update merged in this week, though. One of the primary goals of this re-write was to get this packaging stuff right, and obviously properly managing dependencies is a big part of that.

**Comment by chrisallenlane** [comment]
#480 has been merged, so I'll now close this as moot. Thanks again for reporting it.

**Comment by MadeOfMagicAndWires** [comment]
Cheers!
