### ISSUE TITLE
github.com/tj/front dependency is maybe unnecessary

### ISSUE THREAD

**Issue by TomasKorbar** [cheat/cheat#490]
Hi @chrisallenlane,
I'm making new rpm package of cheat and everything goes well except one thing. In your new version of cheat written in go you use go package `tj/front`, which is not packaged in Fedora. I would not ask you to remove it and simply package it into Fedora but it seems a little overkill for a package, which contains 1 function. It does not even have properly referenced license which is a requirement for a rpm package. So i ask you, could you please implement this function yourself in cheat?

**Comment by chrisallenlane** [comment]
Hi, @TomasKorbar 

As always, thanks for your help "upstream". I just have a few questions:

>  In your new version of cheat written in go you use go package tj/front, which is not packaged in Fedora.

Will you explain what you mean by "packaged in Fedora" here? To my knowledge, the Github repository is canonical. I don't believe there is a more "official" repository elsewhere, as may be the case with `npm` for example.

>  It does not even have properly referenced license which is a requirement for a rpm package.

The [README][] displays an "MIT" badge, though I see that the project does not actually include a `LICENSE.txt` file (or a working hyperlink to the full text of the MIT license).

Does the presence of the badge satisfy Fedora's concerns, or must the project include a `LICENSE` file?

You're right in that re-implementing this would not be a large undertaking, so I'm not strongly averse to doing it. If the presence of the "MIT" badge solves the licensing concern, however, I'm happy to leave `cheat` as-is.

Thanks.

[README]: https://github.com/tj/front

**Comment by TomasKorbar** [comment]
> Will you explain what you mean by "packaged in Fedora" here? To my knowledge, the Github repository is canonical. I don't believe there is a more "official" repository elsewhere, as may be the case with npm, for example.

Sure. Packaged in Fedora means that some software has it's own repository at [0] where is stored it's specfile, patches and whatever is needed for downstream build. You can look at the specfile which i used for building cheat 2 here [1]. According to this specfile is then built rpm package which is uploaded to fedora's repositories (for example [2]). Fedora package manager `dnf` uses files stored in "/etc/yum.repos.d" to find those repositories. And all this in the endgame results in that you can execute `$sudo dnf install cheat` and cheat will be installed on your fedora system. This is what it means for a software to be packaged in Fedora. But before it can be included in those repositories it has to meet conditions described in [3] and another maintainer has to review your specfile.
Hope the answer is not too long:)

> The README displays an "MIT" badge, though I see that the project does not actually include a LICENSE.txt file (or a working hyperlink to the full text of the MIT license).
> Does the presence of the badge satisfy Fedora's concerns, or must the project include a LICENSE file?

Yeah i noticed the badge. To be honest i never had to find this out but you too must feel that if we are asking ourselves this question then something is not right. IMHO it does not satisfy license requirements. 

> or must the project include a LICENSE file?

[4]. Tldr it is strongly encouraged. 

Feel free to ask anything else. I'm happy to help.

[0] - https://src.fedoraproject.org
[1] - https://src.fedoraproject.org/rpms/cheat/blob/master/f/cheat.spec
[2] - https://archives.fedoraproject.org/pub/fedora/linux/releases/31/Everything/x86_64/os/Packages/
[3] - https://docs.fedoraproject.org/en-US/packaging-guidelines/
[4] - https://docs.fedoraproject.org/en-US/packaging-guidelines/LicensingGuidelines/#_license_text

**Comment by chrisallenlane** [comment]
@TomasKorbar, thanks very much for the detailed explanation. I don't have any "upstream" experience, so it's always interesting to hear how those processes work.

Removing this dependency shouldn't be a problem. I'll try to make the change in the next few days, and will update this ticket once I have published the new release.

Thanks!

**Comment by chrisallenlane** [comment]
@TomasKorbar, I've removed the dependency in version `3.0.5`. Please try it out. Thanks :slightly_smiling_face:

**Comment by chrisallenlane** [comment]
Actually, skip `3.0.5` and go to `3.0.6`, please :smile:

**Comment by exploide** [comment]
@TomasKorbar now that this is resolved, may I ask if you plan to package cheat v3 any time soon? Or is there still an issue somewhere?

**Comment by TomasKorbar** [comment]
Yes, it is in my todo list. Unfortunately i'm busy with a different work now, which along with my study consumes all of my time. Hopefully this or next week i will be able to finish new package but i do not want to promise anything. Sorry for the delay.

**Comment by TomasKorbar** [comment]
@exploide @chrisallenlane 
New package is ready at https://copr.fedorainfracloud.org/coprs/tkorbar/cheat/
If anyone is using fedora 31 or higher then i would be glad to have some feedback.
I tested it and it seems to work fine. I will leave it a few days in copr and then i will submit update to fedora 31 and rawhide.

**Comment by exploide** [comment]
@TomasKorbar thank you a lot!

I had a look on the package and the spec file. To be honest, I have a few concerns regarding the "default" cheatsheets (this could also be an answer to #517):

With cheat v3, the community maintained cheatsheets have been broken out into a separate repository. I think this happened for a reason. For example in my case, I really appreciate this, since I do not use them. I use cheat exclusively for my personal cheatsheets. The package you built now contains the community cheatsheets again.

Personally, it wouldn't package them at all and let users fetch them from GitHub. But I might be a bit opinionated about this. Alternatively, they should at least be contained in a separate package that one needs to install explicitly.

Regarding the config file, #501 is related. I would prefer to have cheat create a working default config in the home directory on first run (for an empty cheatsheets dir) as described there. This could also partially address the issues described in #517, because users need to configure cheat manually when using community provided cheatsheets. But I see that opinions might differ on this :/ In any case, I think that installing the cheat tool should do nothing with community cheatsheets (hence, do not create a config file pointing to them). I would expect a installation that is the most clean possible. And currently it contains files from a different, optional repository.

Concerning the autocompletion files, I see it the other way around. It does not harm if you install a few autocompletion files directly from the main cheat package (instead of the -bash, -fish and eventually -zsh subpackages). Users would have working autocompletion out of the box. But it is of course up to you how you package this project, just wanted to explain what I would expect :)

**Comment by exploide** [comment]
I'm not sure if I should post this in #501, #517 or in this issue here, but I want to note down my idea for a first run experience of cheat :sweat_smile:  :

```
$ cheat
It appears you have run cheat for the first time.
I created a config file for you at ~/.config/cheat/conf.yml and a directory to store cheatsheets at ~/.cheat.

Go ahead and note down all the stuff you frequently fail to remember.
Run "cheat -e <sheetname>" to create and edit your first cheatsheet.

If you would like to use a community maintained collection of cheatsheets, you can find one at https://github.com/cheat/cheatsheets.
```

Then, the README of cheat/cheatsheets could better explain how to add this collection to the config file.

**Comment by chrisallenlane** [comment]
@TomasKorbar, thanks for your hard work :tada: 

@TomasKorbar, @exploide: thanks for your remarks here. Let's close this ticket and move the remaining discussion over to #517 so we can keep the conversation in one place. I'll reply with some thoughts there now.
