### ISSUE TITLE
How to ignore files/dotfiles?

### ISSUE THREAD

**Issue by zeitchef** [cheat/cheat#492]
Dotfiles are being listed by cheat as cheatsheet files (eg. .DS_Store) - anyway
to ignore these?

**Comment by chrisallenlane** [comment]
That's weird. `cheat` should be ignoring dotfiles by default:

https://github.com/cheat/cheat/blob/2c0099c28aac69b4d6a74c08ac539982e535bdc9/internal/sheets/load.go#L51-L54

Please show me the output from the following commands:

```sh
cheat -v
```

```sh
cheat -d
```

Thanks.

**Comment by zeitchef** [comment]
Sure thing, @chrisallenlane.

```
// cheat -v
3.0.3

// cheat -d
community: /Users/scott/.cheat/community
work: /Users/scott/.cheat/word
personal: /Users/scott/.cheat/personal
```

Running `cheat -l` lists dotfiles along with cheatsheets.

![Screen Shot 2019-11-05 at 08 59 19](https://user-images.githubusercontent.com/6670659/68188948-a2a8b780-ffaa-11e9-80f3-aa6642fc3e76.png)

**Comment by chrisallenlane** [comment]
Oh, OK - I think I see what's happening here:

The current check simply looks for a `.` at the start of `title`. The intention was to prevent `.git` directories from being recognized as cheatsheets, but I didn't consider `.DS_Store` and other files that may end up polluting a sheet repository.

Your `.DS_Store` "cheatsheets" are all nested within other subdirectories, like `rb/.DS_Store`. Because the `.` isn't the first character in `title` in such cases, the current check will fail.

So, yeah, that's a bug. Thanks for sharing this information. I'll get a patch worked up in the next day or two.

**Comment by chrisallenlane** [comment]
@zeitchef, thanks again for reporting this. This should now be resolved in version `3.0.4`. Please upgrade and let me know if you encounter any further errors.

**Comment by zeitchef** [comment]
@chrisallenlane - thanks for the speedy response! Works as expected on my side.

**Comment by chrisallenlane** [comment]
Excellent :+1:
