### ISSUE TITLE
Background colors in terminal

### ISSUE THREAD

**Issue by exploide** [cheat/cheat#498]
**A description of the problem**

It appears that the formatting and syntax highlighting also includes background colors.  See the following screenshot.

![tty-colors](https://user-images.githubusercontent.com/5670236/68290277-f9d08a00-0087-11ea-9280-50ad47641f69.png)

This happens regardless of the style I set in `conf.yml` (respective colors can be different, though).

I think this looks odd, since terminal output almost always has no background color, so I would expect that for cheat as well.

Is this on purpose or a bug? I noticed that [chroma v0.6.8](https://github.com/alecthomas/chroma/releases/tag/v0.6.8) fixes something concerning background colors and TTYs. Don't know if this is relevant here. But cheat currently uses chroma v0.6.7 according to `go.mod`.

**cheat version info**

3.0.4

**Comment by chrisallenlane** [comment]
Oh - that's a great catch. Thanks!

Some context on this one:

Prior to releasing `cheat` v3 (the Go re-write), I encountered this issue and reached out to the `chroma` author, hoping for advice. In addition to advice, he was kind enough to change the default behavior of `chroma` (within just a few hours!) such that it would no longer apply background-colors when writing to a TTY. (This was the change you referenced in the recent `chroma` commit history.)

It looks like when we began using vendored modules, though, we chose the wrong `chroma` version. I didn't notice this, because I'm using `solarized-dark` for both my terminal and my cheatsheet lexer, so the background color was invisible to me.

Anyway, great catch - this is an annoying problem. It's resolved now in `3.0.6` :tada:
