### ISSUE TITLE
could not locate config file 

### ISSUE THREAD

**Issue by GarrettStanford21** [cheat/cheat#524]
I am on a MacOS.

I am running into an issue with cheat. I installed it via homebrew:
`brew install cheat`

But for any command I get `could not locate config file`

the output of cheat -v: `3.2.2`
The output of cheat -d: `could not locate config file`
The contents of your conf.yml file: I am not sure what this is

Thanks!

**Comment by chrisallenlane** [comment]
Hi, @GarrettStanford21 

Yeah, it's a known-issue right now that `cheat` is too difficult to set up for first-time users. We have a thread going about this here:

https://github.com/cheat/cheat/issues/501

I should be able to make progress on the problem this week. I had hoped to get to it sooner, but had to take on an urgent-priority task at work that has consumed all of my time for the past few weeks.

Regarding solving your problem in the near-term, though - you just need to generate a config file. Try running this command:

```sh
mkdir -p ~/.config/cheat && cheat --init > ~/.config/cheat/conf.yml
```

After that, I'd advise that you read that newly-created file, because there's a lot of documentation in there regarding getting set up initially.

Also note that you'll probably want to clone the community-sourced cheatsheets somewhere, and specify those paths in the config file:

https://github.com/cheat/cheatsheets

Sorry for the headache. I'll try to get this smoothed out in the near-term.

I'm going to close this ticket as "resolved", but feel free to re-open it if you need anything else.

**Comment by josephernest** [comment]
I have the same problem on Windows: 

![image](https://user-images.githubusercontent.com/6168083/72986693-1360b280-3de9-11ea-99f5-44beed7bf475.png)

I don't want to create config files in c:\Users\User\Documents\.cheat\ because I want to keep it portable. 

What is the common way to install it on Windows?

PS: I use https://github.com/cheat/cheat/releases/download/3.3.0/cheat-windows-amd64.exe

**Comment by chrisallenlane** [comment]
Hi, @josephernest 

To be clear, when you say "portable", do you mean on a USB drive, in a [PortableApps][pa] kind of setup?

One solution to explore: `cheat` honors a `CHEAT_CONFIG_PATH` envvar for the specification of the config file path:

https://github.com/cheat/cheat#confyml

If you're only working on one or two shells (perhaps a static desktop somewhere, and within a shell on your portable device), you could set that envvar to point to the config file on your USB drive.

Does that sound plausible? I'm making assumptions about your setup here.

[pa]: https://portableapps.com/

**Comment by chrisallenlane** [comment]
@josephernest, back to your questions, though:

> What is the common way to install it on Windows @chrisallenlane?

I'll confess that I haven't actually tested `cheat` on Windows, as I don't presently have access to a Windows machine. (I'm relying on the community for this.) My understanding, though, is that users simply have been downloading the compiled executable and stashing it somewhere convenient.

> PS2: it would be great to have it create config files if not present (thus avoiding a strange error for new users), do you think it could be possible?

Yeah, this is in the works. See that #501 ticket for details. I had hoped to get this done sooner, but I've been working overtime for the past month or so. I should be able to begin chipping away at this soon, though.

> Anyway congratulations for your project!

Thanks! There are still some rough-edges, but it's coming along :slightly_smiling_face:

**Comment by josephernest** [comment]
> I'll confess that I haven't actually tested cheat on Windows, as I don't presently have access to a Windows machine. (I'm relying on the community for this.) My understanding, though, is that users simply have been downloading the compiled executable and stashing it somewhere convenient.

Unfortunately, currently it doesn't (I just retried on a new Windows machine), it really gives this:

![](https://user-images.githubusercontent.com/6168083/72986693-1360b280-3de9-11ea-99f5-44beed7bf475.png)

Thanks a lot if a Windows user has a solution / or can improve the ready-to-useness :-)

**Comment by sergeevabc** [comment]
Using ```cheat``` on Windows for the first time is a stressful experience.
What one expects is to download, then run like ```cheat tar```, then get a relevant reference.
Instead one sees a long confusing error line such as
```failed to load config: failed to resolve symlink: C:\Users\Name\cheat\cheatsheets\community: CreateFile C:\Users\Name\cheat: The system cannot find the file specified.```
WTF?!

**Comment by bernermic** [comment]
Hi @sergeevabc,
constructive feedback is welcome. Thanks for the report.
What will not help are negative comments. Here are people spending their free time to make a tool to help us all 😉
