### ISSUE TITLE
Support space in cheatpath.

### ISSUE THREAD

**Issue by roachsinai** [cheat/cheat#549]
**A description of the problem**

My cheatpath has a SPACE, and I use `\` to escape it, which works fine in shell. But I got error when use `cheat`: 

`failed to load config: failed to resolve symlink: /home/roach/Nutstore\ Files/.cheat/: lstat /home/roach/Nutstore\ Files: no such file or directory`

The alternative way is use `''` surround(inspired from shell format, too) the cheatpath, which works for `cheat`.

So, is there a way to let ESCAPE SPACE works?

**cheat version info**

version:3.8.0

**cheat configuration info**

```
  - name: personal
    path: /home/roach/Nutstore Files/.cheat/
    tags: [ personal ]
    readonly: false
```

**Comment by chrisallenlane** [comment]
I _think_ this will work if you escape the path in your config as well. Try:

```
path: /home/roach/Nutstore\ Files/.cheat/
```

**Comment by roachsinai** [comment]
![Failed](https://user-images.githubusercontent.com/9500049/77657749-acaa7180-6fb0-11ea-90f5-005b49e1533d.gif)

No, it doesn't work.

**Comment by chrisallenlane** [comment]
I'm investigating this now. I actually can't reproduce this problem on my system. What operating system are you using?

**Comment by roachsinai** [comment]
KDE, Manjaro 19.0.2.

**Comment by chrisallenlane** [comment]
Update: I still can't reproduce this issue on my machine, but I'm not going to close the ticket. Perhaps inspiration will strike me, or perhaps someone else will encounter the same issue.

In the meantime, I'll pin this ticket so it gains more visibility. Maybe someone cleverer than me can suggest steps to reproduce the problem.

**Comment by roachsinai** [comment]
```
hmank ~/Downloads » ./cheat-linux-amd64 -e vim.tab_
failed to load config: failed to resolve symlink: /home/roach/Nutstore\ Files/.cheat/: lstat /home/roach/Nutstore\ Files: no such file or directory
```

Hi, @chrisallenlane as you can see I just download the binary from release page, and don't know why can't work! And I have no experience on Go, before when cheat was wrote by Python I could debug it my self. LOL.

**Comment by chrisallenlane** [comment]
@roachsinai, here's a shot in the dark: let's see if this could be related to your terminal's character encoding. Please run the following in your shell and reply here with the output:

```sh
echo $LC_CTYPE
echo $LANG
```

**Comment by roachsinai** [comment]
@chrisallenlane the output is,

```
hmank ~ » echo $LC_CTYPE

hmank ~ » echo $LANG
zh_CN.UTF-8
hmank ~ » 
```

**Comment by roachsinai** [comment]
Same error on Manjaro xfce: `failed to load config: failed to resolve symlink: /home/xq/Nutstore\ Files/我的坚果云/.cheat/: lstat /home/xq/Nutstore\ Files: no such file or directory`

**Comment by chrisallenlane** [comment]
@roachsinai, thanks for the additional information. I still haven't had time to really dig into this, but FYI, this problem is near the top of the `cheat` priority list. (I just haven't had much time for open-source recently.)

My best guess is that maybe the Chinese characters are somehow the cause of the problem. (Or, rather, `cheat`'s failure to handle them correctly.) I vaguely remember something occurring in `cheat`'s past, back in the Python days? I'll do some searching through the issue tracker as soon as I'm able. Perhaps something will jog my memory.

**Comment by roachsinai** [comment]
Okay, thanks in advanced!

**Comment by chrisallenlane** [comment]
@roachsinai 

I've looked into this further, and I still can't reproduce the problem. It appears as if `cheat` handles all of the following correctly:

- Spaces in filenames
- Chinese characters
- A `LANG` environment value of `zh_CN.UTF-8`
- Using `.cheat` to store cheatsheets

New question: how did you install `cheat`? Download the executable from Github? `go get`? `snap` image? Docker container? That's all I can think of at this point.

**Comment by roachsinai** [comment]
I'm on Manjaro, so using `yay -S cheat`, and the page of cheat on AUR is https://aur.archlinux.org/packages/cheat/

**Comment by zxdvd** [comment]
I think there is no need to escape space in yaml. This is different from shell.

**Comment by roachsinai** [comment]
@zxdvd wow, confirmed that:

```
    path: /home/roach/Nutstore Files/我的坚果云/.cheat
    path: '/home/roach/Nutstore Files/我的坚果云/.cheat'
    path: "/home/roach/Nutstore Files/我的坚果云/.cheat"
```

All three setting above works. I can't even remember I had tried the first setting (I think I should but failed, not sure for this).

But there is a time that the second setting not work!

Anyway all these works right now! Thanks for remind.

Cheers, @chrisallenlane @zxdvd

**Comment by chrisallenlane** [comment]
Oh, fantastic. Thanks, @zxdvd!

**Comment by roachsinai** [comment]
Got below error when upgrade cheat to 4.4.0 from 4.2.5:

```
failed to list cheatsheets: failed to load cheatsheets: failed to load sheet: ssh, path: /home/xq/Nutstore Files/.cheat/ssh, err: failed to parse front-matter: failed to unmarshal frontmatter: yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `tags [ ...` into sheet.frontmatter
```

my config is:

```
  - name: personal
    path: /home/xq/Nutstore Files/.cheat
    tags: [ personal ]
    readonly: false
```

and `'/home/xq/Nutstore Files/.cheat'`  `"/home/xq/Nutstore Files/.cheat"` doesn't works either.

**Comment by chrisallenlane** [comment]
Hi, @roachsinai. Good to hear from you again.

Sorry about this problem. This isn't actually a regression in `4.4.0`, but it rather corrects some _previously faulty_ behavior that looks like a regression.

In brief, you probably have some YAML errors in your community cheatsheets (and any personal cheatsheets that were cloned from the community cheatsheets) due to some errors that were committed a while ago. (These errors have since been fixed.)

To get you fully up-to-speed, please read the thread attached to this ticket:
https://github.com/cheat/cheat/issues/708#issuecomment-1315959024

I'd like to improve how `cheat` handles YAML errors in cheatsheets, but this is somewhat tricky to do due to issues that I don't have time to go into here.

Sorry about the headache, and please let me know if that helps!

**Comment by roachsinai** [comment]
Ah, @chrisallenlane thanks! Sorry for not  replying in time, works well after I removed `---` from .cheat/ssh.

**Comment by chrisallenlane** [comment]
Great to hear. Thanks!
