### ISSUE TITLE
Make "title" overridable in sheet markdown header

### ISSUE THREAD

**Issue by gharry-bsd** [cheat/cheat#564]
Hello,

thanks a lot for cheat, I'm new to it but I very much like it's simplicity and single-binary concept.

> Is your feature request related to a problem? Please describe.

I don't have any Go knowledge, but as far as my shiftless code inspection revealed, there's only "Tags" and "Syntax" as markdown attributes available atm.

> Describe the solution you'd like
I'd like to be able to set a different title than the file name forces currently, by

`---`
`Title: shorter/longer/different_than_filename`
`---`

Thanks,
-harry

**Comment by chrisallenlane** [comment]
Hi, @gharry-bsd 

I'd have to take a look at the code, but this is probably doable.

May I ask to see a specific example of your desired use-case? I want to make sure that I understand the problem correctly before heading down this path. It's not immediately obvious to me why one would prefer to do this over giving the cheatsheet file itself the desired name, though that's likely due to a failure of imagination on my part.

Thanks.

**Comment by chrisallenlane** [comment]
This has gone stale, so I'll close this ticket for now.
