### ISSUE TITLE
Confused about where files get saved

### ISSUE THREAD

**Issue by apenngrace** [cheat/cheat#574]
What is the purpose of the `~/.cheat` folder vs. the `~/.config/cheat/cheatsheets/personal` folder?  

I created a new cheatsheet for myself, like this `cheat -e terminal`.  I would have expected it to be saved in my `personal` folder, but it was saved in the `.cheat` folder.

Thanks.  I really the idea of this, and I'd like to better understand the rationale.

**Comment by chrisallenlane** [comment]
Hello

They solve fundamentally different problems. One directory stores configuration data for the `cheat` executable, and the other stores your cheatsheets.

There's a bit of nuance to understand here.

> What is the purpose of the ~/.cheat folder

In general, `cheat` executable configs likely live here. That said, configs needn't _strictly_ live here. `cheat` honors the [XDG specification][xdg] in where it attempts to locate config information. If you squint at the code a bit, you can see where it checks for configs:

https://github.com/cheat/cheat/blob/master/internal/config/paths.go

> vs. the ~/.config/cheat/cheatsheets/personal folder?

There's nothing special about this path. In your config file, you may specify any arbitrary number of locations at which cheatsheets may be found. You can store cheatsheets in your home directory, your "My Documents" folder, on your desktop - it doesn't matter. These paths can be whatever you like.

If you have "competing" cheatsheets that appear in several directories, `cheat` will (by default) display the one that comes "latest" in your config file. This is useful because it's quite common for folks to have "community" cheatsheets and "personal" cheatsheets, and, presumably, users would consider their personal cheatsheets to be higher priority.

[The README][readme] talks about this in a bit more detail.

Does that make sense?

[readme]: https://github.com/cheat/cheat#cheatpaths
[xdg]: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by chrisallenlane** [comment]
I'm going to close this ticket, but feel free to re-open it if you have further questions. Thanks.
