### ISSUE TITLE
About completions

### ISSUE THREAD

**Issue by apenngrace** [cheat/cheat#575]
How do the completions work?  Will I get completions based on the cheatsheets?

**Comment by chrisallenlane** [comment]
[The README][readme] talks briefly about this.

Unfortunately, I can't go into detail regarding specifically how to configure this, because I've found that there's a huge amount of nuance here, given the vast number of shells available. That said, the most general advice I can give is to find the appropriate completion script in the `scripts` directory and... install it however is appropriate for your shell :neutral_face: 

I'm sorry for the poor documentation here. Perhaps one day we could improve it, but I've been reluctant to take that on. It's likely going to be an undertaking.

[readme]: https://github.com/cheat/cheat#advanced-usage

**Comment by chrisallenlane** [comment]
Generally speaking, though - yeah, you'll get varying autocompletion support in the different shells. To my knowledge, all (supported) shells should be able to autocomplete cheatsheet names.
