### ISSUE TITLE
Where can I find syntax value options to my files?

### ISSUE THREAD

**Issue by bartier** [cheat/cheat#614]
**Is your feature request related to a problem? Please describe.**
I'm not sure if it is documented anywhere what can be the options to put in the YAML section in the `syntax` field. I'm quite new to cheat CLI and I couldn't find possible values.

I would like to format the cheats with Markdown, is it possible?

Thanks!

**Comment by chrisallenlane** [comment]
Hi, @bartier 

Sorry for the delay getting back to you.

> I'm not sure if it is documented anywhere what can be the options to put in the YAML section in the syntax field.

I did a poor job in documenting this. The only "documentation" I have is in the comments of the default config file:

https://github.com/cheat/cheat/blob/1eb44e8809226edf96c09f64b7b2d4c0d6d0f5fd/configs/conf.yml#L8-L11

Because `cheat` uses `chroma` for syntax-highlighting, the values you're looking for are those supported by `chroma`. They're available here:

https://github.com/alecthomas/chroma/tree/master/styles

(Values are simply the filenames minus the `.go` extension.)

> I would like to format the cheats with Markdown, is it possible?

This was discussed [previously][1], but I never did figure out an elegant way to implement this. For now, I would recommend simply writing your cheatsheets in Markdown, and then piping them into some other formatting application:

```sh
cheat foo | some-markdown-formatter
```

I hope that's helpful. Feel free to re-open this ticket if you have any questions.

[1]: https://github.com/cheat/cheat/issues/494
