### ISSUE TITLE
Use "v<SemVer>" format for tagging versions

### ISSUE THREAD

**Issue by etanot** [cheat/cheat#645]
**Type:** Discussion

Is there any specific reason to not prefixing tags with `v`? I mean, as far as I've seen most Go projects use `v<SemVer>` format for tagging. Even using `v` prefix for tagging is encouraged by [Go community](https://dave.cheney.net/2016/06/24/gophers-please-tag-your-releases). Why we're not adopting this?

/cc @chrisallenlane

**Comment by chrisallenlane** [comment]
Hi, @vipkr 

`cheat` is an old project that was originally written in Python. The tagging convention is essentially therefore just a legacy artifact. I'm aware that the project does not conform to the Go conventions, and it bothers me.

With that said, I'm reluctant to change the tagging system now, mostly out of fear that doing so would cause confusion or complexity, rather than reduce it.

To your knowledge, does our lack of conformance to the Go conventions cause any real-world problems, perhaps pertaining to build tools, packaging tools, or the like? If so, I'd be willing to consider migrating to the Go standard. Otherwise, I'm inclined to leave good enough alone here.

Thanks.
