### ISSUE TITLE
Listing cheats forces pager on latest Debian/Ubuntu

### ISSUE THREAD

**Issue by vaporup** [cheat/cheat#681]
Hi,

I have the following issue with Ubuntu 22.04 and Debian 11.
(Haven't tried later Distro versions)

Listing the cheats forces a paging which can't be scrolled or finished.  
No keystroke works. Only quitting the program.

```
cheat -l
```

```
cryptsetup                /root/.config/cheat/cheatsheets/community/cryptsetup                community
csplit                    /root/.config/cheat/cheatsheets/community/csplit                    community
cups                      /root/.config/cheat/cheatsheets/community/cups                      community
--More--
```

On older versions it just works fine. No paging appears

```
cryptsetup                /root/.config/cheat/cheatsheets/community/cryptsetup                community
csplit                    /root/.config/cheat/cheatsheets/community/csplit                    community
cups                      /root/.config/cheat/cheatsheets/community/cups                      community
```

I am not sure what the cause is.
This is what I tested with current (4.2.5) cheat release:

# Debian 11 (broken)

```
tput -V
ncurses 6.2.20201114
```

# Ubuntu 22.04 (broken)

```
tput -V
ncurses 6.3.20211021
```

# Ubuntu 20.04 (works)

```
tput -V
ncurses 6.2.20200212
```

**Comment by chrisallenlane** [comment]
Hi, @vaporup 

Thanks for reporting this. A friend reported something similar a few days ago.

Question: how did you install `cheat` initially? I'm unclear if the issue is with the executable itself, or perhaps with one of the packages.

Regarding solving your problem:

This is probably happening in the newest version of `cheat` because I changed the default pager from `less` to `more` in order to better support Windows out-of-the-box.

You should be able to either `export PAGER=less` in your shell environment, or simply configure the pager in the cheat configuration file. That should be you back up and running in the short-term.

Thanks for reporting this issue, however. We need the default configuration to work on all platforms, so this is definitely worth fixing.

**Comment by vaporup** [comment]
I just downloaded the linux binary. Changing pager via environment didn't work but changing it in the config did. Thanks for the workarournd

**Comment by chrisallenlane** [comment]
OK, great. Thanks for the info. I'll take a look at that this week.

**Comment by chrisallenlane** [comment]
@vaporup, I'm having a hard time reproducing this. Do you know if the `more` pager was installed on the box that initially had the problem? What's your output of `which more`? Thanks.

**Comment by chrisallenlane** [comment]
I'm pinning this one and tagging it has `help-wanted` because I'd like others' eyes on it as well.

**Comment by chrisallenlane** [comment]
Well, I simply can't make `more` behave the way I'd hope/expect on Linux systems. I don't know if I'm doing something wrong, or if  there's a bug in `more`, or what.

With that said, the `4.2.6` release works around this problem:
https://github.com/cheat/cheat/releases/tag/4.2.6

I'm simply burying `more` here when looking for pagers on Linux systems, and I'm no longer  setting it as the default pager. With that said, it's possible that user a will still encounter this error if the following conditions are met:

1. They're using a Linux system
2. They have not configured a pager
3. `more` is available on the `PATH`
4. `more` exhibits the problem described in this ticket (which doesn't happen everywhere)

For the unlucky souls that meet the criteria above and happen to encounter this issue, please just specify a pager in the cheat config file.
